Feature/hero
PavelNedoshyvko/goit-markup-team-project-1 pull request #3
Opened 2023-06-01 19:54 UTC by KRB-U

пофіксити scroll down лишилося

2023-06-01 19:54 UTC, KRB-U commented
подивіться чи icons.svg не полетіли.

2023-06-03 15:15 UTC, PavelNedoshyvko requested changes

2023-06-03 15:15 UTC, PavelNedoshyvko commented on src/css/hero.css
> +@media only screen and (min-width: 376px) {
Не верный меда запрос
изменить min-width: 375px

2023-06-03 15:15 UTC, PavelNedoshyvko commented on src/css/hero.css
> +@media only screen and (min-width: 769px) {
Не верный меда запрос
изменить min-width: 768px

2023-06-03 15:15 UTC, PavelNedoshyvko commented on src/css/hero.css
> +@media only screen and (min-width: 439px) {
Что это?
Откуда появились 439px?

2023-06-03 18:55 UTC, PavelNedoshyvko commented
Нужно пофиксить все баги

2023-06-04 06:15 UTC, KRB-U commented on src/css/hero.css
> +  max-width: 1200px;
прибрав

2023-06-04 06:17 UTC, KRB-U commented on src/css/hero.css
> +  min-width: 295px;
не фіксив

2023-06-04 06:17 UTC, KRB-U commented on src/css/hero.css
> +@media only screen and (min-width: 439px) {
для лінка scroll down та іконки біля нього зробив медіа правило.

2023-06-04 07:54 UTC, PavelNedoshyvko approved these changes

2023-06-04 07:54 UTC, merged