Feature/header
PavelNedoshyvko/goit-markup-team-project-1 pull request #4
Opened 2023-06-02 09:01 UTC by KRB-U

2023-06-03 13:40 UTC, PavelNedoshyvko requested changes

2023-06-03 13:40 UTC, PavelNedoshyvko commented on src/css/header.css
> +  transition: transform 250ms cubic-bezier(0.4, 0, 0.2, 1);
Для времени и кривой в переходах и анимациях у нас в проекте есть переменная
Строка 117 должна выглядеть так transition: transform var(--cubic-bezier);
Исправить во всех transition

2023-06-03 13:40 UTC, PavelNedoshyvko commented on src/css/styles.css
> +  /* --primary-container-width-mobile: 335px; */
Удалить комментарий

2023-06-03 13:40 UTC, PavelNedoshyvko commented on src/partials/header.html
> +    </header>
Лишний тег
Удалить

2023-06-03 18:56 UTC, PavelNedoshyvko commented
Пофиксить все баги

2023-06-04 06:17 UTC, KRB-U commented on src/css/base-styles.css
> +/*
розкомітив

2023-06-04 06:18 UTC, KRB-U commented on src/css/base-styles.css
> +  /* width: 100%; */
розкомітив

2023-06-04 06:18 UTC, KRB-U commented on src/css/styles.css
> +  /* --primary-container-width-mobile: 335px; */
розкосітив

2023-06-04 06:18 UTC, KRB-U commented on src/css/styles.css
> +  /* --primary-container-width-mobile: 335px; */
*розкомітив

2023-06-04 07:53 UTC, PavelNedoshyvko approved these changes

2023-06-04 07:53 UTC, merged